jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # تأكد من استخدام النسخة 18 أو أعلى

    - name: Install dependencies
      run: npm install

    - name: Deploy to Firebase Hosting
      run: npx firebase-tools@latest deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
